### ISSUE TITLE
Older Version

### ISSUE THREAD

**Issue by limelect** [groehner/guipy#1] opened 2022-03-08 17:20 UTC
I would like to compile with 10.2.3
There are some staff of the new ver
Is there an older version?
Furthermore
1. I made an event (key) then I deleted it on the editor
    It does not disappear in the Object Inspector.
2. how do you make an execute?
3. while playing with the demo closed it then pressed text diff it bring an old demo file error
4. new form project >textdiff>cancel right white screen. should stay black no editor
5. close project. make new GUI application put new in an old directory
    bad since it makes old dir full of new projects. not sensible
6. New GUI project no save !!!! Ha Ha save under project but before I did not save it
   puts the file in old dir
7. New GUI save no new folder why? it is new !!
8. Save as not in recent files list
9. Untitled.psproj where is the project? i saved it????
10. How do I open closed form?????????????
11. closing the application things changed why not ask yes no?
12. I will wait for better appliaction
13. keep watching I will add staff

**Comment by groehner** [comment] 2022-03-08 21:48
I would like to compile with 10.2.3
There are some staff of the new ver
Is there an older version?

No, because this is Version 1.0.0 

Furthermore

1.     I made an event (key) then I deleted it on the editor.   It does not disappear in the Object Inspector.
Don't edit create_widgets manually, it's not designed for this purpose. Editing is done in the GUI form and the object inspector.

2.     how do you make an execute?
What exactly are you asking for? Is#t this:
https://datatofish.com/executable-pyinstaller/
Perhaps it's possible to configure a new Tool (Menu Tools/Tools/Configure Tools)

3.     while playing with the demo closed it then pressed text diff it bring an old demo file error
4.      new form project >textdiff>cancel right white screen. should stay black no editor
This this bug is fixed in the next version

6.     close project. make new GUI application put new in an old directory
       bad since it makes old dir full of new projects. not sensible
A new GUI application isn't put in an olde directory, it exists only in the editor until you explicit save it. 
And then it's your responsibility to save it at a proper destination.
  
    
8.     New GUI project no save !!!! Ha Ha save under project but before I did not save it
10.     puts the file in old dir
As i already said, a new GUI project isn't saved until you save it or you close GuiPy.
The Caption shows the default path for the GUI project if you save it.

11.     New GUI save no new folder why? it is new !!
It's your responsibility to save it in the desired folder. GuiPy doesn't know which one you want.

13.     Save as not in recent files list
By design. Only closed files are added to the recent file list. Save as doesn't close the file, so it's not necessary to pen it via the recent file list.

15.     Untitled.psproj where is the project? i saved it????
I'll have to take a look at that soon

17.     How do I open closed form?????????????
This is explaind in the documentation. 
[](https://guipy.de/lib/exe/detail.php?id=start&media=arrange.png)Use the icon of the source code editor to open the associated GUI form.

19.     closing the application things changed why not ask yes no?
You can configure this under Options/Save files automatically
In my opinion by default i want that my work is saved. 

21.     I will wait for better appliaction
22.     keep watching I will add staff

**Comment by limelect** [comment] 2022-03-09 07:54
17 found it OK thanks ain't it better to put it in a TAB? 
2 how to make an execute I mean make a program exe

6 for some reason, while playing with the software, I filled an old directory with new staff
I did not save I did open close a few times.

I can see in recent files put in c:\user\....documents   why?

well, the program has great potential !!!! keep up the good work

**Closed** 2022-03-10 21:09 UTC

**Comment by groehner** [comment] 2022-03-11 07:48
Sorry, I don't understand "I can see in recent files put in c:\user....documents why?"

An update to version 1.0.1 is available.

**Comment by limelect** [comment] 2022-03-14 07:22
Somehow while "playing" with the software i
got your files in this directory
c:\user....document
![Screenshot - 14_03_2022 , 09_20_49](https://user-images.githubusercontent.com/4199131/158123564-2efe79ab-a5b8-4db0-abbb-af73bc74adfc.jpg)
